yum_cluster_packages:
  - ruby
  - rubygems
  - ruby-devel
  - rpm-build
  - zlib-devel
os_service_dir: /usr/lib/systemd/system


redis_service_str: >-
  [
  {% if redis_deploy_type == 'cluster' -%}
  {% for item in range(0,redis_cluster_node_port_size) -%}
  {
  port: "{{ redis_cluster_begin_port + item | int }}",
  dir: "{{ redis_data_path }}/{{ redis_cluster_begin_port + item | int }}",
  conf: "{{ redis_data_path }}/{{ redis_cluster_begin_port + item | int }}/redis.conf",
  pid: "{{ redis_data_path }}/{{ redis_cluster_begin_port + item | int }}/redis.pid",
  log: "{{ redis_cluster_begin_port + item | int }}.log",
  script: "{{ redis_data_path }}/{{ redis_cluster_begin_port + item | int }}/redis{{ redis_cluster_begin_port + item | int }}.sh",
  service: "{{ os_service_dir }}/redis{{ redis_cluster_begin_port + item | int }}.service"
  }
  {{ ',' if redis_cluster_node_port_size > item + 1 else '' }}
  {%- endfor %}
  {%- endif %}
  ]

redis_service: "{{ redis_service_str | from_yaml }}"