---
- name: Install | Confirm the redis installation package has been downloaded
  stat: path={{ redis_file_path }}
  register: redis_file_result

- name: Install | Confirm the redis installation package download directory exists
  file: path={{ redis_download_path }} state=directory
  when: not redis_file_result.stat.exists

- name: Install | Download the redis installation package
  get_url: url={{ redis_file_url }} dest={{ redis_download_path }}
  when: not redis_file_result.stat.exists

- name: Install | Confirm the redis installation directory exists
  file: path={{ redis_install_path }} state=directory

- name: Install | Unzip redis to the specified directory
  unarchive:
    src: "{{ redis_file_path }}"
    dest: "{{ redis_install_path }}"
    copy: "no"
    mode: "0755"
    owner: root
    group: root

- name: Install | Build redis.
  shell: "cd {{ redis_src_path }}/src && make && make install"
