---
- name: Configure | Cluster -> install yum cluster packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ yum_cluster_packages }}"
  when:
  - inventory_hostname == groups[all_redis_node_group][0]
  - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Configure | Cluster -> install redis gems.
  gem:
    name: redis
    state: present
    version: 3.0.0
    user_install: no
  when: inventory_hostname == groups[all_redis_node_group][0]

- name: Configure | Cluster -> Del yes or no the option.
  lineinfile:
    regexp: '        yes_or_die \"Can I set the above configuration\?\"'
    line: '        #yes_or_die "Can I set the above configuration?"'
    path: "{{ redis_src_path }}/src/redis-trib.rb"

- name: Configure | Cluster -> create cluster
  shell: >
    {{ redis_src_path }}/src/redis-trib.rb create --replicas {{ redis_cluster_replicas }} {% for item in groups[all_redis_node_group] -%}
    {% for service in redis_service -%}
    {{ hostvars[item]['ansible_ssh_host'] }}:{{service.port}}{{ redis_cluster_trib_separator }}
    {%- endfor %}
    {%- endfor %}
  when: inventory_hostname == groups[all_redis_node_group][0]
