---
- name: reset | include configure vars
  include_vars: "../configure/defaults/main.yml"

- name: reset | stop and disable redis service.
  service: "name=redis{{ item.port }} state=stopped enabled=no"
  with_items: "{{ redis_service }}"
  ignore_errors: yes

- name: reset | delete Redis service.
  file:
    path: "{{ item.service }}"
    state: absent
  with_items: "{{ redis_service }}"
  ignore_errors: yes

- name: reset | delete some files and directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ redis_data_path }}"
    - "{{ redis_src_path }}"
    - "/usr/local/bin/redis-benchmark"
    - "/usr/local/bin/redis-check-aof"
    - "/usr/local/bin/redis-check-rdb"
    - "/usr/local/bin/redis-cli"
    - "/usr/local/bin/redis-sentinel"
    - "/usr/local/bin/redis-server"
  ignore_errors: yes