---
all_redis_node_group: "redis"

redis_name: "redis"
redis_version: "4.0.1"

redis_download_path: "/tmp"
redis_install_path: "/usr/local"
redis_src_path: "{{ redis_install_path }}/{{ redis_name }}-{{ redis_version }}"
redis_data_path: "/opt/redis"

redis_file: "{{ redis_name }}-{{ redis_version }}.tar.gz"
redis_file_url: "http://download.redis.io/releases/{{ redis_file }}"
redis_file_path: "{{ redis_download_path }}/{{ redis_file }}"

# redis 部署类型
# cluster 是 Redis的分布式解决方案
redis_deploy_type: 'cluster'

# redis cluster 模式配置
redis_cluster_node_port_size: 2
redis_cluster_min_port_size: 6
redis_cluster_begin_port: 7000
redis_cluster_replicas: 1
redis_cluster_trib_separator: " "

# redis 密码
redis_passwd: "123456"

# 日志记录等级，4个可选值debug,verbose,notice,warning
# 可以是下面的这些值：
# debug (适用于开发或测试阶段)
# verbose (many rarely useful info, but not a mess like the debug level)
# notice (适用于生产环境)
# warning (仅仅一些重要的消息被记录)
redis_log_level: notice
redis_log_dir: /export/logs/redis